POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "username": "Guilherme",
  "email": "guilherme@gmail.com",
  "password": "senha123"
}

###

GET http://localhost:3000/api/v1/users/guilherme

###

GET https://rossik.dev.br/api/faker?count=100

###
PATCH  http://localhost:3000/api/v1/users/Guilherme
Content-Type: application/json

{
  "username": "Guilherme11",
  "email": "guilherme11@gmail.com"
}